export type Article={tag:string,title:string,intro:string,cover:string,coverAlt:string,inline:string,inlineAlt:string,sections:[string,string][]};
export const articles:Article[]=[
 {tag:'STUDY ABROAD',title:'A Practical Guide to University Admissions, Scholarships and Student Budgets',intro:'Explore how to compare programs, organize applications, understand scholarships, and prepare for the real costs of studying abroad.',cover:'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1400&q=85',coverAlt:'Students and university building',inline:'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1200&q=85',inlineAlt:'Study books on a table',sections:[
 ['Understand your academic goals','Choosing a university starts with the subject you want to study and the work you hope to do afterwards. Review the complete curriculum instead of judging a program by a ranking or advertising slogan. Look for required modules, research opportunities, practical assignments, and academic support. International applicants should also check whether their prior qualifications meet the institution’s published entry requirements. Keep the official course page bookmarked so you can verify any information you see elsewhere.'],
 ['Compare admission requirements carefully','Applications can require transcripts, references, language test results, portfolios, and personal statements. These requirements vary by course and may change between application cycles. Make a spreadsheet with a separate row for each program and record deadlines, required documents, application fees, and available contact details. Do not assume that requirements for one course apply to every program at the same university.'],
 ['Build a realistic student budget','Tuition is only one part of the cost of studying overseas. Depending on the country and city, students may also pay for housing deposits, meals, local transport, books, health coverage, travel, and immigration applications. Compare several accommodation options and make an estimate for recurring monthly expenses. A small emergency fund can help cover unexpected travel or replacement equipment without interrupting your studies.'],
 ['Find scholarships through official sources','Start with each university’s financial aid or scholarships page. Read eligibility rules, covered expenses, academic requirements, and renewal conditions. Some awards cover only a fraction of tuition, while others may also include living expenses; labels such as “fully funded” should be checked against the actual award terms. Never pay an unknown intermediary who promises a guaranteed scholarship.'],
 ['Organize your application timeline','Create a calendar of application openings, document deadlines, language tests, scholarship deadlines, and decision dates. Leave time to request references and obtain official transcripts. Once you submit an application, save its confirmation number and keep copies of submitted materials. If a university requests additional information, respond through its verified admissions portal rather than unknown messaging accounts.'],
 ['Prepare before departure','After accepting an offer, review the institution’s pre-arrival checklist. You may need to arrange accommodation, insurance, travel documents, and student orientation. Read your destination country’s official entry guidance and confirm your arrival plans with the university. Planning these details early lets you focus on your course once the semester begins.']]},
 {tag:'TECH & CAREERS',title:'Digital Skills, Online Learning and Practical Career Planning',intro:'A detailed learning roadmap for choosing digital skills, finding useful training, building a portfolio, and evaluating career opportunities.',cover:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=85',coverAlt:'Team collaborating with a laptop',inline:'https://images.unsplash.com/photo-1516321165247-4aa89a48be28?auto=format&fit=crop&w=1200&q=85',inlineAlt:'Student working on a laptop',sections:[
 ['Choose a specific goal first','The internet offers countless tutorials, but learning becomes easier when you decide what you want to create. Someone interested in websites can start with HTML, CSS, accessibility, and basic JavaScript. Someone interested in data can practice spreadsheets, charts, and introductory statistics. A clear goal helps you reject courses that are unrelated to your current needs.'],
 ['Follow a manageable learning routine','Consistency often matters more than buying an expensive course. Divide a larger skill into smaller lessons and reserve a little time each week for hands-on practice. At the end of each session, write down what you learned and where you got stuck. If a topic still feels unclear, revisit the official documentation and rebuild the example without copying every step.'],
 ['Build real examples of your work','A small completed project shows more than a list of watched videos. Try building a mobile-friendly landing page, an expense dashboard, an organized document template, or an edited short video. Keep the source files and note what you would improve in a second version. Projects also help reveal which parts of the work you genuinely enjoy.'],
 ['Evaluate online courses and certificates','Before enrolling, check who teaches the course, what the syllabus covers, and whether sample lessons are available. A certificate may help demonstrate study effort, but it does not guarantee employment. Compare the course material with current documentation and look for assignments that require you to use the skill independently rather than just pass multiple-choice quizzes.'],
 ['Present a clear portfolio','Select a few representative projects and explain the problem, tools, and result for each. Screenshots, short walkthroughs, and concise descriptions make it easier for others to understand your contribution. Do not include confidential work or personal information without permission. Update your portfolio as you improve instead of keeping every unfinished experiment online.'],
 ['Stay alert to unrealistic offers','Treat promises of instant earnings, guaranteed jobs, or unusually high returns with caution. Verify companies through official websites and independently listed contact details. Legitimate opportunities should clearly explain the responsibilities, working arrangements, and selection process. Keep improving your skills while comparing multiple career paths.']]},
 {tag:'TRAVEL & PLANNING',title:'An International Travel Checklist: Documents, Insurance, Budget and Safety',intro:'Plan an international trip with a practical checklist covering entry rules, travel insurance, accommodation, spending, and emergency arrangements.',cover:'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1400&q=85',coverAlt:'Traveler looking at a map',inline:'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=85',inlineAlt:'Landscape near a travel destination',sections:[
 ['Confirm passport and entry requirements','Begin with official government or embassy information for your destination. Passport validity, transit rules, proof of onward travel, and visa requirements may differ depending on nationality and travel purpose. Recheck these conditions before departure because travel rules and appointment availability can change. Store important confirmation emails in a secure location.'],
 ['Read travel insurance details','Insurance products differ in coverage limits, exclusions, deductibles, and claims procedures. Compare emergency medical coverage, trip interruption, baggage protection, and any restrictions related to planned activities. A cheap policy can become costly if it excludes the very situation you need covered. Keep the insurer’s assistance number accessible during the trip.'],
 ['Estimate the full cost','Budget for flights, local transport, accommodation, meals, activities, mobile connectivity, and unexpected expenses. Exchange-rate changes can affect the final amount you spend abroad. Before booking, check cancellation terms and whether quoted prices include taxes and service fees. Consider multiple transport options instead of relying on the first advertised fare.'],
 ['Choose accommodation thoughtfully','Read recent traveler feedback but verify the property through the booking provider’s official page. Check its location relative to transport and your planned activities. Look for a clear cancellation policy, check-in hours, and any extra deposits. Keep booking details available offline in case you lose mobile connectivity on arrival.'],
 ['Create a simple safety plan','Share a basic itinerary with someone you trust and learn the local emergency number for your destination. Protect original documents and avoid posting their images publicly. Use reputable transport providers and be cautious about unsolicited offers that require immediate payment. These basic habits can reduce avoidable stress during travel.'],
 ['Pack and prepare for arrival','Make a packing checklist based on the climate, baggage allowance, and activities you actually plan to do. Confirm airport transfers and the address of your first accommodation. If you take essential medication, review applicable travel requirements well in advance. Allow extra time during connections so minor delays do not disrupt the rest of your itinerary.']]}
];
