"use client";
import {useState} from 'react';
export type DirectLink={id:string;label:string;url:string;enabled:boolean};
export default function DirectLinksManager({initial}:{initial:DirectLink[]}){
 const [rows,setRows]=useState(initial),[label,setLabel]=useState(''),[url,setUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function api(path:string,method:string,body?:unknown){const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
 async function add(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await api('/api/admin/direct-links','POST',{label,url});setRows(prev=>[d.link,...prev]);setLabel('');setUrl('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function update(row:DirectLink,patch:Partial<DirectLink>){setError('');try{const d=await api(`/api/admin/direct-links/${row.id}`,'PATCH',patch);setRows(prev=>prev.map(x=>x.id===row.id?d.link:x));}catch(e){setError((e as Error).message)}}
 async function remove(row:DirectLink){if(!confirm(`Delete ${row.label}?`))return;setError('');try{await api(`/api/admin/direct-links/${row.id}`,'DELETE');setRows(prev=>prev.filter(x=>x.id!==row.id));}catch(e){setError((e as Error).message)}}
 return <section className="panel"><h2>Direct Link Manager</h2><p className="muted">Add multiple approved Monetag Direct Links. One active URL is randomly selected each time a visitor page loads. Both sponsored buttons in that popup point to the same chosen URL. Ads are optional; neither button is a fake Continue action.</p><form onSubmit={add}><div className="grid"><label>Label<input className="input" maxLength={100} required value={label} onChange={e=>setLabel(e.target.value)} placeholder="Campaign 1" /></label><label>HTTPS Direct Link URL<input className="input" type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." /></label></div><button className="btn" disabled={busy}>Add Direct Link</button></form>{error&&<p className="alert" role="alert">{error}</p>}<div className="direct-admin-list">{rows.map(row=><div className="direct-admin-row" key={row.id}><strong>{row.label}</strong><small className="truncate-url">{row.url}</small><div className="direct-actions"><label><input type="checkbox" checked={row.enabled} onChange={e=>update(row,{enabled:e.target.checked})}/> Enabled</label><button type="button" className="btn gray" onClick={()=>{const value=prompt('Direct Link URL',row.url);if(value!==null)update(row,{url:value})}}>Edit URL</button><button type="button" className="btn gray" onClick={()=>{const value=prompt('Campaign name',row.label);if(value!==null)update(row,{label:value})}}>Rename</button><button type="button" className="btn danger" onClick={()=>remove(row)}>Delete</button></div></div>)}</div></section>;
}
