'use client';
import {useEffect,useState} from 'react';
type Summary={earnedCents:number;availableCents:number;pendingCents:number;paidCents:number;impressions:number;ecpm:number|null};
type Entry={date:string;cents:string;impressions:string};type Payout={id:string;cents:string;status:string;date:string};
type Data={summary:Summary;entries:Entry[];payouts:Payout[]};
const usd=(v:number)=>'$'+(v/100).toFixed(2);
export default function EarningsWidget(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[amount,setAmount]=useState('10.00'),[busy,setBusy]=useState(false);
 async function refresh(){try{const r=await fetch('/api/account/earnings',{cache:'no-store'});if(!r.ok)throw Error('Earnings are temporarily unavailable');setData(await r.json())}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void refresh()},[]);
 async function requestPayout(e:React.FormEvent){e.preventDefault();const cents=Math.round(Number(amount)*100);if(!Number.isSafeInteger(cents)||cents<1000){setError('Minimum payout request is $10');return}setBusy(true);setError('');try{const r=await fetch('/api/account/payouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amountCents:cents})});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to request payout');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel"><h2>My earnings</h2><p className="muted">Your share of verified ad revenue. Amounts are shown in USD; page views are not paid impressions. Recent figures may be adjusted before crediting.</p>{!data?<p>{error||'Loading earnings…'}</p>:<><div className="grid"><div className="stat"><small>Available balance</small><h2>{usd(data.summary.availableCents)}</h2></div><div className="stat"><small>Total earnings</small><h2>{usd(data.summary.earnedCents)}</h2></div><div className="stat"><small>Pending payout</small><h2>{usd(data.summary.pendingCents)}</h2></div><div className="stat"><small>Average CPM (your share)</small><h2>{data.summary.ecpm===null?'—':'$'+data.summary.ecpm.toFixed(2)}</h2></div></div><p className="muted">Verified ad impressions: {data.summary.impressions.toLocaleString()} · Paid out: {usd(data.summary.paidCents)}</p><form onSubmit={requestPayout}><label>Request payout (USD, minimum $10)<input className="input" type="number" min="10" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><button className="btn" disabled={busy||data.summary.availableCents<1000}>Request withdrawal</button></form><small>Requests are reviewed manually. Contact the administrator to arrange payment details securely; no automatic transfers are made.</small>{error&&<p role="alert" className="alert">{error}</p>}<h3>Earnings history</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Date</th><th>Your earnings</th><th>Ad impressions</th></tr></thead><tbody>{data.entries.map((x,i)=><tr key={i}><td>{x.date.slice(0,10)}</td><td>{usd(Number(x.cents))}</td><td>{Number(x.impressions).toLocaleString()}</td></tr>)}</tbody></table></div><h3>Withdrawal requests</h3><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Requested</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data.payouts.map(x=><tr key={x.id}><td>{x.date.slice(0,10)}</td><td>{usd(Number(x.cents))}</td><td>{x.status}</td></tr>)}</tbody></table></div></>}</section>
}
