'use client';

import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import EarningsWidget from '@/components/EarningsWidget';

type LinkRow = { id: string; slug: string; destination: string; title: string; enabled: boolean; clicks: number; created_at?: string };
type ApiKey = { id: string; name: string; key_prefix: string; created_at: string; last_used_at: string | null; revoked_at: string | null };
type DailyVisit = { day: string; visits: number };
type Tab = 'overview' | 'links' | 'analytics' | 'earnings' | 'api';

const compact = (n: number) => new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 }).format(n);
function Glyph({ name, size = 20 }: { name: string; size?: number }) {
  const paths: Record<string, ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,
    link: <><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></>,
    chart: <><path d="M3 3v18h18"/><path d="m7 16 4-5 4 3 5-8"/></>,
    wallet: <><rect x="2" y="5" width="20" height="16" rx="3"/><path d="M2 9h20M17 15h2"/><path d="M5 5V3h14"/></>,
    key: <><circle cx="8" cy="15" r="4"/><path d="m11 12 9-9 2 2-2 2-2-2-3 3 2 2-2 2-2-2"/></>,
    plus: <path d="M12 5v14M5 12h14"/>,
    eye: <><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></>,
    copy: <><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></>,
    arrow: <path d="M7 17 17 7M8 7h9v9"/>,
    logout: <><path d="M10 17l5-5-5-5m5 5H3"/><path d="M12 3h6a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3h-6"/></>,
    menu: <path d="M4 6h16M4 12h16M4 18h16"/>,
    close: <path d="M5 5l14 14M19 5 5 19"/>,
    search: <><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></>,
    shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] || paths.grid}</svg>;
}

function ActivityChart({ daily }: { daily: DailyVisit[] }) {
  const max = Math.max(1, ...daily.map(x => Number(x.visits) || 0));
  const points = daily.map((x, i) => `${24 + i * (600 / Math.max(1, daily.length - 1))},${178 - ((Number(x.visits) || 0) / max) * 142}`).join(' ');
  const total = daily.reduce((sum, x) => sum + Number(x.visits), 0);
  return <div className="pro-chart" role="img" aria-label={`Visitor traffic during the last seven days: ${total} recorded visits`}>
    <div className="pro-chart-head"><div><h3>Traffic overview</h3><p>Recorded link visits · Last 7 days (UTC)</p></div><span className="pro-chip">Last 7 days</span></div>
    <div className="pro-chart-graph"><div className="pro-axis">{[max, Math.round(max / 2), 0].map((v, i) => <span key={i}>{compact(v)}</span>)}</div><div className="pro-chart-plot">
      <svg viewBox="0 0 648 200" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="visit-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3f74f5" stopOpacity=".23"/><stop offset="100%" stopColor="#3f74f5" stopOpacity="0"/></linearGradient></defs><path d="M24 36H624M24 107H624M24 178H624" stroke="#e9eef7" strokeDasharray="5 5"/><polygon points={`24,178 ${points} 624,178`} fill="url(#visit-fill)"/><polyline points={points} fill="none" stroke="#4a76ef" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/>{daily.map((d, i) => <circle key={d.day} cx={24 + i * (600 / Math.max(1, daily.length - 1))} cy={178 - ((Number(d.visits) || 0) / max) * 142} r="4.5" fill="#fff" stroke="#4a76ef" strokeWidth="2.5"/>)}</svg>
      <div className="pro-chart-labels">{daily.map(d => <span key={d.day}>{new Date(d.day + 'T12:00:00Z').toLocaleDateString('en-US', { weekday: 'short', timeZone: 'UTC' })}</span>)}</div>
    </div></div>
  </div>;
}

export default function UserDashboard({ email, initialLinks, initialKeys, dailyVisits, totals }: { email: string; initialLinks: LinkRow[]; initialKeys: ApiKey[]; dailyVisits: DailyVisit[]; totals: {links:number; visits:number; active:number} }) {
  const [links, setLinks] = useState(initialLinks), [keys, setKeys] = useState(initialKeys);
  const [destination, setDestination] = useState(''), [title, setTitle] = useState(''), [alias, setAlias] = useState(''), [keyName, setKeyName] = useState(''), [secret, setSecret] = useState('');
  const [tab, setTab] = useState<Tab>('overview'), [mobileNav, setMobileNav] = useState(false), [search, setSearch] = useState(''), [status, setStatus] = useState(''), [busy, setBusy] = useState(false);
  const [stats, setStats] = useState(totals);
  const totalVisits = Number(stats.visits);
  const activeLinks = Number(stats.active);
  const filtered = useMemo(() => links.filter(l => [l.slug, l.title, l.destination].some(v => (v || '').toLowerCase().includes(search.toLowerCase()))), [links, search]);
  async function run(path: string, method: string, body?: unknown) { const r = await fetch(path, { method, headers: { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || 'Request failed'); return data; }
  async function addLink(e: FormEvent) { e.preventDefault(); setBusy(true); setStatus(''); try { const result = await run('/api/account/links', 'POST', { destination, title, slug: alias }); setLinks(prev => [{ ...result.link, clicks: 0 }, ...prev]); setStats(prev => ({...prev, links: prev.links + 1, active: prev.active + (result.link.enabled ? 1 : 0)})); setDestination(''); setTitle(''); setAlias(''); setStatus('Short link created successfully.'); } catch (err) { setStatus((err as Error).message); } finally { setBusy(false); } }
  async function copyLink(slug: string) { try { await navigator.clipboard.writeText(`${location.origin}/s/${slug}`); setStatus('Short URL copied to clipboard.'); } catch { setStatus('Could not copy automatically. Please copy the URL manually.'); } }
  async function toggleLink(l: LinkRow) { try { const result = await run(`/api/account/links/${l.id}`, 'PATCH', { enabled: !l.enabled }); setLinks(prev => prev.map(x => x.id === l.id ? { ...x, ...result.link } : x)); setStats(prev => ({...prev, active: prev.active + (l.enabled ? -1 : 1)})); } catch (err) { setStatus((err as Error).message); } }
  async function deleteLink(l: LinkRow) { if (!confirm(`Delete ${l.title || l.slug}? This cannot be undone.`)) return; try { await run(`/api/account/links/${l.id}`, 'DELETE'); setLinks(prev => prev.filter(x => x.id !== l.id)); setStats(prev => ({...prev, links: prev.links - 1, active: prev.active - (l.enabled ? 1 : 0), visits: Math.max(0, prev.visits - Number(l.clicks || 0))})); setStatus('Link deleted.'); } catch (err) { setStatus((err as Error).message); } }
  const nav: { id: Tab; text: string; icon: string }[] = [{ id: 'overview', text: 'Overview', icon: 'grid' }, { id: 'links', text: 'My links', icon: 'link' }, { id: 'analytics', text: 'Analytics', icon: 'chart' }, { id: 'earnings', text: 'Earnings', icon: 'wallet' }, { id: 'api', text: 'API keys', icon: 'key' }];
  function selectTab(next: Tab) { setTab(next); setMobileNav(false); setStatus(''); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  const linkTable = (rows: LinkRow[]) => <div className="pro-table-scroll"><table className="pro-table"><thead><tr><th>Short link</th><th>Destination</th><th>Visits</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={5} className="pro-empty">No links here yet. Create your first short link above.</td></tr> : rows.map(l => <tr key={l.id}><td><div className="pro-link-title">{l.title || l.slug}</div><a href={`/s/${encodeURIComponent(l.slug)}`} target="_blank" rel="noreferrer" className="pro-short">/s/{l.slug} <Glyph name="arrow" size={13}/></a></td><td><span className="pro-destination" title={l.destination}>{l.destination}</span></td><td><strong>{Number(l.clicks || 0).toLocaleString()}</strong></td><td><span className={`pro-status ${l.enabled ? 'is-active' : ''}`}>{l.enabled ? 'Active' : 'Disabled'}</span></td><td><div className="pro-actions"><button type="button" title="Copy short URL" onClick={() => void copyLink(l.slug)}><Glyph name="copy" size={16}/></button><button type="button" onClick={() => void toggleLink(l)}>{l.enabled ? 'Disable' : 'Enable'}</button><button type="button" className="pro-danger-text" onClick={() => void deleteLink(l)}>Delete</button></div></td></tr>)}</tbody></table></div>;
  return <main className="pro-dashboard"><div className="pro-layout">
    <aside className={`pro-sidebar ${mobileNav ? 'pro-open' : ''}`}><a className="pro-logo" href="/"><span className="pro-logo-mark"><Glyph name="link" size={23}/></span><span>Bingo<span>Link</span><small>CREATOR STUDIO</small></span></a><div className="pro-side-label">WORKSPACE</div><nav aria-label="Dashboard navigation">{nav.map(item => <button key={item.id} className={`pro-nav-link ${tab === item.id ? 'selected' : ''}`} onClick={() => selectTab(item.id)}><Glyph name={item.icon} size={19}/>{item.text}{tab === item.id && <span className="pro-nav-dot"/>}</button>)}</nav><div className="pro-sidebar-bottom"><a href="/developers" className="pro-nav-link"><Glyph name="key" size={19}/>API documentation</a><div className="pro-sidebar-profile"><span className="pro-avatar">{email.charAt(0).toUpperCase()}</span><span><strong>{email.split('@')[0]}</strong><small title={email}>{email}</small></span></div></div></aside>
    {mobileNav && <button type="button" className="pro-nav-overlay" aria-label="Close navigation" onClick={() => setMobileNav(false)}/>}
    <div className="pro-main"><header className="pro-topbar"><div className="pro-topbar-left"><button type="button" className="pro-mobile-toggle" aria-label="Toggle navigation" onClick={() => setMobileNav(!mobileNav)}><Glyph name={mobileNav ? 'close' : 'menu'}/></button><div className="pro-breadcrumb">Workspace <span>/</span> <strong>{nav.find(n => n.id === tab)?.text}</strong></div></div><div className="pro-topbar-right"><span className="pro-live-indicator"><span/> Account active</span><span className="pro-avatar small">{email.charAt(0).toUpperCase()}</span><button type="button" className="pro-signout" title="Sign out" onClick={async () => { try { await run('/api/auth/logout', 'POST'); location.href = '/login'; } catch (err) { setStatus((err as Error).message); } }}><Glyph name="logout" size={18}/><span>Sign out</span></button></div></header>
      <div className="pro-content"><div className="pro-page-title"><div><div className="pro-eyebrow">YOUR WORKSPACE</div><h1>{tab === 'overview' ? 'Welcome back!' : nav.find(n => n.id === tab)?.text}</h1><p>{tab === 'overview' ? 'Your links, performance and earnings in one place.' : tab === 'links' ? 'Create, share and manage your short links.' : tab === 'analytics' ? 'Real recorded visits to your short links.' : tab === 'earnings' ? 'Your verified earnings and withdrawal requests.' : 'Manage keys for your developer integrations.'}</p></div>{tab !== 'api' && tab !== 'earnings' && <button className="pro-primary-button" onClick={() => selectTab('links')}><Glyph name="plus" size={18}/> New link</button>}</div>
      {status && <div className="pro-notice" role="status">{status}<button type="button" onClick={() => setStatus('')}>×</button></div>}
      {(tab === 'overview' || tab === 'analytics') && <><div className="pro-metric-grid"><div className="pro-metric-card"><div className="pro-metric-icon blue"><Glyph name="link"/></div><span>Total links</span><strong>{compact(Number(stats.links))}</strong><small>Created in your account</small></div><div className="pro-metric-card"><div className="pro-metric-icon purple"><Glyph name="eye"/></div><span>Total visits</span><strong>{compact(totalVisits)}</strong><small>All recorded link visits</small></div><div className="pro-metric-card"><div className="pro-metric-icon green"><Glyph name="shield"/></div><span>Active links</span><strong>{compact(activeLinks)}</strong><small>Currently enabled</small></div><div className="pro-metric-card"><div className="pro-metric-icon orange"><Glyph name="chart"/></div><span>Last 7 days</span><strong>{compact(dailyVisits.reduce((a, b) => a + Number(b.visits), 0))}</strong><small>Visits · UTC</small></div></div><ActivityChart daily={dailyVisits}/></>}
      {(tab === 'overview' || tab === 'links') && <><div className="pro-section-header"><div><h2>{tab === 'overview' ? 'Create a short link' : 'New short link'}</h2><p>Turn long URLs into secure, shareable BingoLink links.</p></div></div><section className="pro-card pro-create-card"><form onSubmit={addLink}><label className="pro-field pro-full"><span>Destination URL <em>*</em></span><input type="url" required value={destination} onChange={e => setDestination(e.target.value)} placeholder="https://example.com/your-long-link"/></label><div className="pro-form-row"><label className="pro-field"><span>Link title <small>optional</small></span><input maxLength={150} value={title} onChange={e => setTitle(e.target.value)} placeholder="Give this link a name"/></label><label className="pro-field"><span>Custom alias <small>optional</small></span><input maxLength={40} value={alias} onChange={e => setAlias(e.target.value)} placeholder="Leave blank for a random alias"/></label></div><div className="pro-form-footer"><span><Glyph name="shield" size={16}/> Secure link generation enabled</span><button className="pro-primary-button" disabled={busy} type="submit"><Glyph name="plus" size={18}/>{busy ? 'Creating…' : 'Create short link'}</button></div></form></section><div className="pro-section-header pro-recent-title"><div><h2>{tab === 'overview' ? 'Recent links' : 'All your links'}</h2><p>{tab === 'overview' ? 'Your most recently created short links.' : `${filtered.length} links found`}</p></div>{tab === 'overview' ? <button className="pro-text-button" onClick={() => selectTab('links')}>View all →</button> : <label className="pro-search"><Glyph name="search" size={16}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search links" aria-label="Search links"/></label>}</div><section className="pro-card pro-table-card">{linkTable(tab === 'overview' ? links.slice(0, 5) : filtered)}</section></>}
      {tab === 'analytics' && <section className="pro-card pro-analytics-note"><Glyph name="chart" size={25}/><div><h3>How visits are counted</h3><p>These are recorded visits to your short links, not billable ad impressions. Earnings and CPM are based on verified revenue records.</p></div></section>}
      {(tab === 'earnings' || tab === 'overview') && <section className={`pro-earnings-area ${tab === 'overview' ? 'pro-earnings-overview' : ''}`}><EarningsWidget/></section>}
      {tab === 'api' && <><section className="pro-card pro-api-card"><div className="pro-section-header"><div><h2>Developer API keys</h2><p>Generate and manage keys for your applications. Up to five active keys.</p></div><a href="/developers" className="pro-text-button">View API docs →</a></div><form onSubmit={async e => { e.preventDefault(); setBusy(true); setStatus(''); try { const d = await run('/api/account/keys', 'POST', { name: keyName }); setKeys(prev => [d.metadata, ...prev]); setSecret(d.key); setKeyName(''); } catch (err) { setStatus((err as Error).message); } finally { setBusy(false); } }} className="pro-key-form"><label className="pro-field"><span>Key name</span><input required maxLength={80} placeholder="My application" value={keyName} onChange={e => setKeyName(e.target.value)}/></label><button type="submit" className="pro-primary-button" disabled={busy}><Glyph name="plus" size={17}/>Generate key</button></form>{secret && <div className="pro-key-secret" role="status"><strong>Copy this key now. You will not see it again.</strong><code>{secret}</code><button onClick={async () => { await navigator.clipboard.writeText(secret); setStatus('API key copied.'); }} type="button">Copy</button><button type="button" onClick={() => setSecret('')}>Hide</button></div>}</section><section className="pro-card pro-table-card"><div className="pro-inner-heading"><h3>Existing keys</h3></div><div className="pro-table-scroll"><table className="pro-table"><thead><tr><th>Name</th><th>Prefix</th><th>Last used</th><th>Status</th><th>Action</th></tr></thead><tbody>{keys.length ? keys.map(k => <tr key={k.id}><td><strong>{k.name}</strong></td><td><code>{k.key_prefix}…</code></td><td>{k.last_used_at ? new Date(k.last_used_at).toLocaleDateString() : 'Never'}</td><td><span className={`pro-status ${!k.revoked_at ? 'is-active' : ''}`}>{k.revoked_at ? 'Revoked' : 'Active'}</span></td><td>{!k.revoked_at && <button className="pro-revoke" type="button" onClick={async () => { if (!confirm('Revoke this API key?')) return; try { await run(`/api/account/keys/${k.id}`, 'DELETE'); setKeys(prev => prev.map(x => x.id === k.id ? { ...x, revoked_at: new Date().toISOString() } : x)); } catch (err) { setStatus((err as Error).message); } }}>Revoke</button>}</td></tr>) : <tr><td colSpan={5} className="pro-empty">No API keys yet.</td></tr>}</tbody></table></div></section></>}
      <footer className="pro-footer">© {new Date().getFullYear()} BingoLink · Your links, your workspace.</footer></div>
    </div>
  </div></main>;
}
