import {notFound,redirect}from 'next/navigation';
import Link from 'next/link';
import {readProgress}from '@/lib/auth';import{getLink,getSettings,seconds}from '@/lib/data';
import {articles}from '@/lib/articles';
import AdScript from '@/components/AdScript';import ContinueTimer from '@/components/ContinueTimer';
export const runtime='nodejs';export const dynamic='force-dynamic';
export default async function AdPage({params}:{params:Promise<{slug:string,step:string}>}){
const{slug,step:raw}=await params;const step=Number(raw);if(!Number.isInteger(step)||step<1||step>4||!(/^[a-z0-9_-]{3,40}$/.test(slug)))notFound();const l=await getLink(slug);if(!l||!l.enabled)notFound();
const progress=await readProgress();if(!progress||progress.slug!==slug||progress.step!==step)redirect(`/s/${slug}`);
const settings=await getSettings();const article=articles[step-1];const adUrls=settings.ads_enabled==='true'?[settings.monetag_script_url,settings.inpage_script_url].filter(Boolean):[];
return <main className="narrow"><header className="header"><Link className="brand" href="/">🔗 BingoLink</Link><span className="tag">Step {step} of 4</span></header><div className="panel" style={{textAlign:'center'}}><h1>{step===4?'Final step: get your link':article.title}</h1><p className="muted">{step===4?'One short countdown before redirecting.':article.intro}</p></div>{adUrls.length>0&&<AdScript urls={adUrls}/>}<div className="ad"><span className="ad-label">Advertisement</span><p>Advertisements may appear here based on your ad provider’s approved format and available inventory.</p></div>{article?<article className="article panel"><p>{article.intro}</p>{article.sections.slice(0,2).map(([heading,body])=><section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}<div className="ad"><span className="ad-label">Advertisement</span><p>Ad space — placements depend on approved Monetag scripts.</p></div>{article.sections.slice(2).map(([heading,body])=><section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</article>:<div className="panel article"><h2>Before opening the destination</h2><p>You will leave BingoLink when you press Get Original Link. Other websites have their own terms and privacy policies. You do not need to click ads, grant notification permission, or enter personal information to proceed.</p></div>}<ContinueTimer slug={slug} step={step} startedAt={progress.startedAt} seconds={seconds(settings,step)}/><footer className="footer"><Link href="/privacy">Privacy</Link> · <Link href="/terms">Terms</Link> · Ads are separately labeled</footer></main>}
